package com.yuling.app.model;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_id
     *
     * @mbg.generated Sun Jul 29 12:45:52 CST 2018
     */
    private Integer departmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column department.department_Name
     *
     * @mbg.generated Sun Jul 29 12:45:52 CST 2018
     */
    private String departmentName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_id
     *
     * @return the value of department.department_id
     *
     * @mbg.generated Sun Jul 29 12:45:52 CST 2018
     */
    public Integer getDepartmentId() {
        return departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_id
     *
     * @param departmentId the value for department.department_id
     *
     * @mbg.generated Sun Jul 29 12:45:52 CST 2018
     */
    public void setDepartmentId(Integer departmentId) {
        this.departmentId = departmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column department.department_Name
     *
     * @return the value of department.department_Name
     *
     * @mbg.generated Sun Jul 29 12:45:52 CST 2018
     */
    public String getDepartmentName() {
        return departmentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column department.department_Name
     *
     * @param departmentName the value for department.department_Name
     *
     * @mbg.generated Sun Jul 29 12:45:52 CST 2018
     */
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
}